name: Backend CI

on:
  pull_request:
    branches: ["main"]
    paths:
      - backend/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: "8.0"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go 1.24.x
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: "1.24.x"
      - name: Run tests
        run: |
          cd backend
          go test .
