name: End to End Test

on:
  pull_request:
    branches: ["main"]
    paths:
      - frontend/**
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

env:
  MONGODB_URI: mongodb://localhost:27017
  PUBLIC_API_HOST: localhost:8080
  PUBLIC_PROTOCOL: http://
  PUBLIC_WS_PROTOCOL: ws://
  HOST: localhost:4173/BASE_PATH
  PROTOCOL: http://

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: "8.0"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go 1.24.x
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: "1.24.x"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name : Install dependencies
        run: |
          cd frontend
          npm install
      - name: Run tests
        run: |
          npm run test
